//
//  ViewController.m
//  TestOClint
//
//  Created by BOSH on 2019/9/12.
//  Copyright © 2019 BOSH. All rights reserved.
//

#import "ViewController.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    int dsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklk = 3;
    
    int aaaaaaaddsakjdadskjajdkjadhjahdjkhajkdhakjadadbajdhahjdhajdhajkdhjkahdjkahdjahdklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklkklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklklklklklkdsadsklkkklk =0;
    // Do any additional setup after loading the view.
}


- (void)test
{
    NSLog(@"");
}

@end
